[package]
name = "second-best-analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.76"
strum = "0.25.0"
strum_macros = "0.25.3"
